name: Testing
on: push

jobs:
  test_tasks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit test_tasks
    run: |
      pip3 install --users Django
      python3 manage.py test